### ISSUE TITLE
ts-node execute error on windows 10

### ISSUE THREAD

**Issue by icefee** [stormkit-io/stormkit-cli#12]
undefined:1
'{ ^ SyntaxError: Unexpected token ' in JSON at position 0 at JSON.parse () at parse (F:\React\Code-Space-stormkit\node_modules\ts-node\dist\util.js:52:45) at arg (F:\React\Code-Space-stormkit\node_modules\arg\index.js:122:24) at parseArgv (F:\React\Code-Space-stormkit\node_modules\ts-node\dist\bin.js:69:12) at main (F:\React\Code-Space-stormkit\node_modules\ts-node\dist\bin.js:25:18) at Object. (F:\React\Code-Space-stormkit\node_modules\ts-node\dist\bin.js:579:5) at Module._compile (node:internal/modules/cjs/loader:1159:14) at Module._extensions..js (node:internal/modules/cjs/loader:1213:10) at Module.load (node:internal/modules/cjs/loader:1037:32) at Module._load (node:internal/modules/cjs/loader:878:12) Node.js v18.12.1

**Comment by svedova** [comment]
Thanks for submitting this issue @icefee! I'll take a look at this 👀

**Comment by svedova** [comment]
@icefee I just checked out https://github.com/stormkit-dev/sample-project and tried running `npm run dev:api` and it seems to be working: 

![node18-stormkit-cli](https://user-images.githubusercontent.com/3321893/227880584-9be8c370-41fc-42a1-8c96-869eb9111b92.png)

And when I check the browser:

![image](https://user-images.githubusercontent.com/3321893/227880844-3b6bcd4e-d913-458d-8ace-4a97f1236d9b.png)

Now that I check your error message more in detail, I think it may be unrelated to Stormkit. 

I'm closing this issue 👍

**Comment by icefee** [comment]
Thanks for your answer.
The reason has not been confirmed yet.I test it on my pc , Ubuntu virtual machine, working computer, my friend's computer.
Ubuntu worked correctly
all of 3 Windows 10  pc won't work correctly
I will continue to find out the reson and update the issue.

**Comment by icefee** [comment]
@svedova 
It seems a feature of ts-node, that make different behavior in windows and mac os or linux.
[https://github.com/TypeStrong/ts-node/issues/606](https://github.com/TypeStrong/ts-node/issues/606)

**Comment by svedova** [comment]
@icefee thanks for the investigation! I guess it's related to https://github.com/stormkit-io/stormkit-cli/blob/main/src/commands/api-server.ts#L152 then. Would you be kind enough to submit a PR for the fix? Otherwise please let me know, I don't have a Windows PC so I'll have to setup a virtual machine from scratch.

**Comment by icefee** [comment]
@svedova 
I fixed it and tested it on my windows pc.

**Comment by svedova** [comment]
@icefee great work 🚀 🚀 Thanks a lot 🙏
